import "./globals.css";

import styles from "./page.module.css";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body>
				<nav className={styles.nav}>
					<h1>Dashnny</h1>
				</nav>
				<main className={styles.content}>{children}</main>
			</body>
		</html>
	);
}
